# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
    default_config: base_config
    configs:
        base_config:
            toolbar: full
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: [ ]