vich_uploader:
    db_driver: orm

    mappings:
        covered_images:
            uri_prefix: '%app.path.covered_images%'
            namer: vich_uploader.namer_uniqid
            upload_destination: '%kernel.project_dir%/../public%app.path.covered_images%'
