index:
    path: /
    controller : App\Controller\BlogController:index
login:
    path: /login
    controller: App\Controller\SecurityController::login

registration:
    path: /register
    controller: App\Controller\RegistrationController::register
