index:
    path: /
    controller : App\Controller\BlogController:index
login:
    path: /login
    controller: App\Controller\SecurityController::login

registration:
    path: /register
    controller: App\Controller\RegistrationController::register

user_profile:
    path: /user/profile
    controller: App\Controller\UserController::show

user_edit:
    path: /user/profile/edit
    controller: App\Controller\UserController::edit

app_check_email:
    path: /check-email
    controller: App\Controller\ResetPasswordController::checkEmail

app_forgot_password_request:
    path: /reset-password
    controller: App\Controller\ResetPasswordController::request

app_reset_password:
    path: /reset
    controller: App\Controller\ResetPasswordController::reset
# elfinder:
#    resource: "@FMElfinderBundle/Resources/config/routing.yaml"