index:
    path: /
    controller : App\Controller\BlogController:index
login:
    path: /login
    controller: App\Controller\SecurityController::login

registration:
    path: /register
    controller: App\Controller\RegistrationController::register

user_profile:
    path: /user/profile
    controller: App\Controller\UserController::show

user_edit:
    path: /user/profile/edit
    controller: App\Controller\UserController::edit